### ISSUE TITLE
Can you document the armband structure?

### ISSUE THREAD

**Issue by codeWonderland** [ChristianFusco/InspiritFull#1]
I am very interested in this project, but am limited on how much I can interact with it because there are no diagrams as to how one could recreate the arm band.

Is this something that could be included in this repo?

**Comment by ChristianFusco** [comment]
I don't have any great examples of how to put the armband together, and I wouldn't be able to make one since I didn't have a part in putting it together.

I do have the parts list though, and a picture and description in my capstone paper.

I'll upload the paper to the github project, and add the pictures and parts list to the readme.

**Comment by ChristianFusco** [comment]
I made the updates

I'll leave the issue up for a few days.  Let me know if you have anymore questions.
